# Generated by Django 5.2.14 on 2026-05-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0229_series_mergedseries_seriesbook'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seriesbook',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='seriesbook',
            constraint=models.UniqueConstraint(fields=('book', 'series'), name='book_series'),
        ),
        migrations.AddConstraint(
            model_name='seriesbook',
            constraint=models.UniqueConstraint(fields=('series', 'series_number'), name='series_seriesnumber', nulls_distinct=True),
        ),
    ]
